create table users
(
	id bigint generated by default as identity constraint users_pkey primary key,
	name varchar(255) not null,
	login varchar(255) not null constraint uk_login unique,
	password varchar(255) not null
);

create table roles
(
    id bigint generated by default as identity constraint roles_pkey primary key,
    name varchar(255) not null
);

create table user_roles
(
    user_id bigint not null constraint fk_users references users,
    role_id bigint not null constraint fk_roles references roles,
    constraint user_roles_pkey primary key (user_id, role_id)
);

insert into roles(id, name) values
(1, 'admin'),
(2, 'user');

insert into users(id, name, login, password) values
(1, 'Anna','anna','anna1'),
(2, 'Bob','bob','bob1'),
(3, 'Celine','celine','celine1'),
(4, 'David','david','david1');

insert into user_roles(user_id, role_id) values
(1, 1),
(1, 2),
(2, 2),
(3, 2),
(4, 1),
(4, 2);