create sequence client_id_seq;

create sequence phone_seq increment by 50;

create table address
(
	id uuid not null
		constraint address_pkey
			primary key,
	street varchar(255)
);

create table client
(
	id bigint generated by default as identity
		constraint client_pkey
			primary key,
	name varchar(255),
	address_id uuid
		constraint fk_address
			references address
);

create table phone
(
	id bigint not null
		constraint phone_pkey
			primary key,
	number varchar(255),
	client_id bigint not null
		constraint fk_client
			references client
);